"""Run the unified visualization preparation pipeline."""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/autotorch_advanced_visualization_mpl")

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from advanced_visualization.core.pipeline import PipelineOptions, prepare_model_artifact
from advanced_visualization.core.settings import configured_path, load_settings


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prediction-csv", type=Path, default=None)
    parser.add_argument("--model-key", action="append", default=[], help="Model key to run. Defaults to all enabled settings models.")
    parser.add_argument("--batch-size", type=int, default=None, help="Feature extraction batch size.")
    parser.add_argument("--gradcam-batch-size", type=int, default=None, help="Grad-CAM batch size.")
    parser.add_argument("--num-workers", type=int, default=None)
    parser.add_argument("--save-workers", type=int, default=None)
    parser.add_argument("--limit", type=int, default=None, help="Optional Grad-CAM row limit.")
    parser.add_argument("--skip-features", action="store_true")
    parser.add_argument("--skip-gradcam", action="store_true")
    parser.add_argument("--no-only-missing-gradcam", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    settings = load_settings()
    pipeline = settings.pipeline
    selected = set(args.model_key)
    skipped_artifact_only = [
        model.key
        for model in settings.models
        if model.enabled and model.model_type == "artifact_only" and (not selected or model.key in selected)
    ]
    models = [
        model
        for model in settings.models
        if model.enabled
        and model.model_type != "artifact_only"
        and model.resolved_checkpoint() is not None
        and (not selected or model.key in selected)
    ]
    if not models:
        if skipped_artifact_only:
            joined = ", ".join(skipped_artifact_only)
            raise SystemExit(f"Selected model(s) are artifact-only and cannot be pregenerated by AutoTorch: {joined}")
        raise SystemExit("No enabled model-loading settings models selected.")

    for model_key in skipped_artifact_only:
        print(f"{model_key}: skipped artifact-only model")

    options = PipelineOptions(
        batch_size=int(args.batch_size if args.batch_size is not None else pipeline["batch_size"]),
        gradcam_batch_size=int(args.gradcam_batch_size if args.gradcam_batch_size is not None else pipeline["gradcam_batch_size"]),
        num_workers=int(args.num_workers if args.num_workers is not None else pipeline["num_workers"]),
        save_workers=int(args.save_workers if args.save_workers is not None else pipeline["save_workers"]),
        only_missing_gradcam=bool(pipeline["only_missing_gradcam"]) and not args.no_only_missing_gradcam,
        generate_gradcam=bool(pipeline["generate_gradcam"]) and not args.skip_gradcam,
        extract_features=bool(pipeline["extract_features"]) and not args.skip_features,
        cam_methods=tuple(pipeline.get("cam_methods", ["gradcam"])),
        limit=args.limit if args.limit is not None else (int(pipeline["gradcam_limit"]) or None),
    )

    for model in models:
        if model.weights_epoch is None:
            raise SystemExit(f"{model.key}: weights_epoch is required.")
        raw_prediction_csv = str(args.prediction_csv or model.prediction_csv or settings.prediction_csv).strip()
        if not raw_prediction_csv:
            raise SystemExit(f"{model.key}: no prediction CSV configured.")
        prediction_csv = configured_path(raw_prediction_csv)
        result = prepare_model_artifact(
            model_key=model.key,
            artifact_dir=configured_path(model.artifact_dir),
            prediction_csv=prediction_csv,
            weights_epoch=model.weights_epoch,
            options=options,
        )
        print(
            f"{result.model_key}: prepared={result.prepared_csv} "
            f"gradcam generated={result.generated_gradcam} skipped={result.skipped_gradcam} failed={result.failed_gradcam}"
        )


if __name__ == "__main__":
    main()
