training:
  epochs: 100
  batch_size: 32            # 128 fails
  learning_rate: 1e-4       # 1e-4 to 1e-5 typical
  weight_decay: 1e-5        # Optimizer weight decay (prevent overfit) typical is 1e-2 to 1e-5
  loss_fn: bce_with_logits  # cross_entropy, bce, bce_with_logits, mse
  optimizer: adamw          # adam, adamw, sgd

scheduler:                  # learning rate scheduler
  warmup_epochs: 5          # 0 = disable; LR ramps 0 -> full over N epochs
  decay_type: cosine        # 'cosine', 'step', or 'none'
  # StepLR params (if decay_type: step)
  step_size: 10             # decay every N epochs
  gamma: 0.1                # LR multiplier at each step
  # CosineAnnealingLR params (if decay_type: cosine)
  eta_min: 1e-5             # minimum LR at end of cosine cycle

checkpoint:
  enabled: true

early_stopping:
  enabled: true
  patience: 15               # epochs to wait after no improvement
  delta: 0.005               # minimum change in val loss to count as improvement
  verbose: true

model:
  repo_dir: /mnt3/repo_and_weights/repo/dinov3
  backbone_name: dinov3_vits16
  checkpoint_path: /mnt3/repo_and_weights/weights/dinov3_vits16_pretrain_lvd1689m-08c60483.pth
  hidden_units: 384
  freeze_backbone: false
  save_name: testing_moved_paths.pth
  save_dir: ../runs

data:
  train_val_split: 0.9
  train_batches:
    - path/to/batch1/index_annotation.csv
    # - path/to/batch2/index_annotation.csv
    # Add more batches as needed

dataloader:
  num_workers: 4

transform:
  image_size: 512
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
