experiment:
  save_dir: /mnt3/repo_and_weights/runs # use absolute path here 
  save_name: Ex4_van_b0_legacy_512_ori
model:
  backbone_name: van_b0
  freeze_backbone: false
  head_type: legacy
  
training:
  batch_size: 32
  epochs: 100
  learning_rate: 1e-4
  loss_fn: bce_with_logits
  optimizer: adamw
  training_threshold: 0.5
  weight_decay: 0

early_stopping:
  delta: 1e-7
  enabled: true
  patience: 12
  verbose: true

scheduler: 
  warmup_epochs: 0 # no warmup
  decay_type: cosine # available options are 'cosine', 'step' and 'plateau'
  # for decay_type=step:
  gamma: 0.1
  step_size: 10
  # for decay_type=cosine:
  eta_min: 1e-7 
  # for decay_type=plateau
  patience: 5     
  factor: 0.5       
  min_lr: 1e-7
  min_delta: 1e-4       

dataloader:
  num_workers: 24
  prefetch_factor: 10
  pin_memory: true
  non_blocking: true
  persistent_workers: true
  drop_last: true # we need to set this to tra

data:
  image_type: ori
  train_val_split: 0.9
  # sample_fraction: 0.5 
  train_batches:
  - batch_production_202207_redone_rejectedcase/index_annotation.csv
  - batch_production_202209_redone_rejectedcase/index_annotation.csv
  - batch_legacy_20221026_subset/index_annotation_ori.csv
  - batch_datacollection_20230214_none_recapture/batch_datacollection_20230214_recapture_train_set.csv
  - batch_datacollection_20231219_wiseai_recapture_10IC/index_annotation_train_set.csv
  - batch_issue_20230322_none_recapture_colorprint/index_annotation_mykadfront.csv
  - batch_production_20240206_none_1000/index_annotation_mykadfront_annotated_train_set.csv
  - batch_datacollection_20240409_production202207redone_fullpagecolorprinttrain/index_annotation.csv
  - batch_datacollection_20240303_wiseai_recapture_whitepaperbg/index_annotation_WhitePaper_train_set_w_square.csv
  - batch_issue_20240412_partner_both_general/index_annotation_mykadfront.csv
  - batch_issue_20240704_snt_both_colorghostwhitebg/index_annotation_mykadfront.csv
  - batch_issue_20240704_snt_replay/index_annotation_mykadfront.csv
  # - batch_production_20240625_whitebg_genuine/batch_production_20240625_whitebg_genuine.csv
  # found:
  - production_20240625_whitebg_genuine/index_annotations_mykadfront_filtered_train_set.csv
  # - batch_datacollection_202407_production20240625none_whitebg/batch_datacollection_202407_production20240625none_whitebg.csv
  # found:
  - 2024-07-whitebg_fraud/index_annotation_mykadfront_train_set.csv
  # - batch_weakness_20240726_bnm_colorprint/batch_weakness_20240726_bnm_colorprint.csv
  # found:
  - BNM_20240726/index_annotation_mykadfront_Ench12Weakness.csv
  # - batch_datacollection_202408_customdevicevariance/batch_datacollection_202408_customdevicevariance.csv
  # found:
  - 2024-08-custom-device-variance/updated_annotations_train_v2.csv
  - batch_datacollection_20240806_wiseai_both_whitepapercrossplatform/updated_annotations_train.csv
  - batch_issue_20240823_snt_app/index_annotation_mykadfront.csv
  # - batch_datacollection_202411_inkjet_printer/batch_datacollection_202411_inkjet_printer.csv
  # found:
  - 2024-11-inkjet_printer_train/index_annotation_mykadfront.csv
  # - batch_datacollection_202501_inkjet_printer_cutout/batch_datacollection_202501_inkjet_printer_cutout.csv
  # found:
  - 2025-01-inkjet_printer_cutout_train/index_annotation_mykadfront.csv
  - batch_production_20250416_none_mypr/index_annotation_mypr_crop_train.csv
  - batch_production_20250416_none_mytentera/index_annotation_mytentera_crop_train.csv
  - batch_production_20250514_none_mytentera/index_annotation_mytentera_crop_train.csv
  # - batch_datacollection_20250530_printed_cutout/batch_datacollection_20250530_printed_cutout.csv
  # found:
  - 2025-05-printed_cutout/index_annotation_mykadfront_train.csv
  # - batch_datacollection_20250707_fakeid_v2/batch_datacollection_20250707_fakeid_v2.csv
  # found:
  - 2025-07-fakeidtester/index_annotation_mykadfront_train_v2.csv
  # - batch_datacollection_202501_inkjet_printer_cutout_augmentedmaskedbw/batch_datacollection_202501_inkjet_printer_cutout_augmentedmaskedbw.csv
  # found:
  - 2025-01-inkjet_printer_cutout_train/index_annotation_mykadfront_augmented_masked_bw.csv
  - batch_production_20240206_none_1000/index_annotation_mykadfront_annotated_train_set_augmented_masked_bw.csv
  # - grayscale_print_cutout_test_plan_subject/grayscale_print_cutout_test_plan_subject.csv
  # found:
  - 1.4 Grayscale Print Cutout Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - colorprint_cutout_test_plan_subject/colorprint_cutout_test_plan_subject.csv
  # found:
  - 1.5 Color Print Cutout Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - color_print_test_plan_subject/color_print_test_plan_subject.csv
  # found:
  - 1.3 Color Print Test/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - grayscale_print_test_plan_subject/grayscale_print_test_plan_subject.csv
  # found:
  - 1.2 Grayscale Print Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - color_print_with_background2_test_plan_subject/color_print_with_background2_test_plan_subject.csv
  # found:
  - 1.6.1 Color Print with Background 2 Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - replay_monitor_test_plan_subject/replay_monitor_test_plan_subject.csv
  # found:
  - 1.10 Replay Monitor Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - replay_mobile_test_plan_subject/replay_mobile_test_plan_subject.csv
  # found:
  - 1.11 Replay Mobile Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - replay_tablet_test_plan_subject/replay_tablet_test_plan_subject.csv
  # found:
  - 1.12 Replay Tablet Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  # - genuine_with_background_test_plan_subject/genuine_with_background_test_plan_subject.csv
  # found:
  - 1.1 Genuine with Background Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_train.csv
  - 20250804_myekyc_fullday/filtered_annotated_index_annotation_mykadfront_train.csv
  - batch_issue_20250910_bmmb_both_general/index_annotation_mykadfront_v3.csv
  - 20250804_myekyc_fullday/annotated_filtered_annotated_index_annotation_mykadfront_genuine.csv
  - 20250804_myekyc_fullday/annotated_filtered_annotated_index_annotation_mykadfront_print.csv
  - 20250806_myekyc_owntester/annotated_index_annotation_mykadfront_v3_genuine.csv
  - 20250806_myekyc_owntester/annotated_index_annotation_mykadfront_v3_print.csv
  - 20250806_myekyc_owntester/annotated_index_annotation_mykadfront_v3_replay.csv
  - 20250808_genuine&cutout/annotated_index_annotation_genuine.csv
  - 20250808_genuine&cutout/annotated_index_annotation_print_cutout.csv
  - 20250808_replay_tablet/annotated_index_annotation_genuine.csv
  - 20250808_replay_tablet/annotated_index_annotation_replay.csv
  - 20250808_tamper_face/annotated_index_annotation_genuine.csv
  - 20250807_genuine/annotated_index_annotation.csv
  - 20250807_tamper_4/annotated_index_annotation.csv
  - 20250811_genuine_ekyc/filtered_index_annotation.csv
  - 20250811_Replay_FullPage/filtered_index_annotation_v2_print.csv
  - 20250811_Replay_FullPage/filtered_index_annotation_v2_replay.csv
  - 20250811_tamper_face/filtered_index_annotation.csv
  - 20250813_grayscale/annotated_annotated_index_annotation_mykadfront_print.csv
  - 20250813_grayscale/annotated_annotated_index_annotation_mykadfront_replay.csv
  - 20250813_grayscale/annotated_annotated_index_annotation_mykadfront_grayscale.csv
  - 20250813_wiseai_myid_test-dry_run/index_annotation_mykadfront_v4_print.csv
  - 20250813_wiseai_myid_test-dry_run/index_annotation_mykadfront_v4_replay.csv

  eval_batches:
  - 2024-07-whitebg_fraud/index_annotation_mykadfront_test_set.csv
  - 2024-11-inkjet_printer_eval/index_annotation_mykadfront.csv
  - batch_datacollection_20230214_none_recapture/batch_datacollection_20230214_recapture_eval_set.csv
  - batch_datacollection_20231023_wiseai_recapture_evalfixorigrotatealif/index_annotation_full.csv
  - batch_datacollection_20231219_wiseai_recapture_10IC/index_annotation_eval_set.csv
  - batch_datacollection_20240303_wiseai_recapture_whitepaperbg/index_annotation_WhitePaper_eval_set.csv
  - batch_datacollection_20240303_wiseai_recapture_whitepaperbg/index_annotation_WhitePaper_eval_set_square.csv
  - batch_datacollection_20240409_production202208redone_fullpagecolorprinteval/index_annotation_square.csv
  - batch_datacollection_20240409_production202208redone_fullpagecolorprinteval/index_annotation_w_genuine.csv
  - batch_issue_20230322_none_recapture_colorprint/index_annotation_mykadfront.csv
  - batch_issue_20240403_none_recapture_replaymobile/index_annotation_mykadfront.csv
  - batch_issue_20240408_partner_recapture_fullcolorprint/index_annotation_mykadfront.csv
  - batch_issue_20240412_partner_both_general/index_annotation_mykadfront.csv
  - batch_issue_20240704_snt_both_colorghostwhitebg/index_annotation_mykadfront.csv
  - batch_issue_20240704_snt_fullpagecolorprint/index_annotation_mykadfront.csv
  - batch_issue_20240704_snt_replay/index_annotation_mykadfront.csv
  - BNM_20240726/index_annotation_mykadfront_Ench12Issue.csv
  - batch_issue_20240823_snt_app/index_annotation_mykadfront.csv
  - batch_issue_20241202_snt_mobile/index_annotation_mykadfront.csv
  - batch_issue_20241203_postdigi_colorprint/index_annotation_mykadfront.csv
  - batch_issue_set/index_annotation_mykadfront_background.csv
  - batch_production_202208_redone/index_annotation.csv
  - batch_production_20240206_none_1000/index_annotation_mykadfront_annotated_eval_set.csv
  - batch_production_20240405_none_merged/index_annotation.csv
  - SNT_20240513_20240519_random/index_annotation_mykadfront_filtered.csv
  - production_20240625_whitebg_genuine/index_annotations_mykadfront_filtered_test_set.csv
  - BNM_20240726/index_annotation_mykadfront_processed_filtered.csv
  - batch_production_20250416_none_mypr/index_annotation_mypr_crop_eval.csv
  - batch_production_20250416_none_mytentera/index_annotation_mytentera_crop_eval.csv
  - batch_production_20250514_none_mytentera/index_annotation_mytentera_crop_eval.csv
  - 2025-05-printed_cutout/index_annotation_mykadfront_eval.csv
  - 2025-07-fakeidtester/index_annotation_mykadfront_eval_v2.csv
  - 2025-01-inkjet_printer_cutout_eval/index_annotation_mykadfront_augmented_masked_bw.csv
  - batch_production_20240206_none_1000/index_annotation_mykadfront_annotated_eval_set_augmented_masked_bw.csv
  - 1.4 Grayscale Print Cutout Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.5 Color Print Cutout Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.3 Color Print Test/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.2 Grayscale Print Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.6.1 Color Print with Background 2 Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.10 Replay Monitor Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.11 Replay Mobile Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.12 Replay Tablet Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 1.1 Genuine with Background Test Plan/cleaned_filtered_annotated_index_annotation_jpg_subject_mykadfront_test.csv
  - 20250804_myekyc_fullday/annotated_filtered_annotated_index_annotation_mykadfront_genuine.csv
  - 20250804_myekyc_fullday/annotated_filtered_annotated_index_annotation_mykadfront_print.csv
  - 20250805_myekyc_fullday/annotated_index_annotation_mykadfront_cutout.csv
  - 20250805_myekyc_fullday/annotated_index_annotation_mykadfront_genuine.csv
  - 20250805_myekyc_fullday/annotated_index_annotation_mykadfront_printed.csv
  - 20250805_myekyc_fullday/annotated_index_annotation_mykadfront_replay.csv
  - 20250806_myekyc_owntester/annotated_index_annotation_mykadfront_v3_genuine.csv
  - 20250806_myekyc_owntester/annotated_index_annotation_mykadfront_v3_print.csv
  - 20250806_myekyc_owntester/annotated_index_annotation_mykadfront_v3_replay.csv
  - "20250808_genuine&cutout/annotated_index_annotation_genuine.csv"
  - "20250808_genuine&cutout/annotated_index_annotation_print_cutout.csv"
  - 20250808_replay_tablet/annotated_index_annotation_genuine.csv
  - 20250808_replay_tablet/annotated_index_annotation_replay.csv
  - 20250808_tamper_face/annotated_index_annotation_genuine.csv
  - 20250807_genuine/annotated_index_annotation.csv
  - 20250807_tamper_4/annotated_index_annotation.csv
  - 20250811_genuine_ekyc/filtered_index_annotation.csv
  - 20250811_Replay_FullPage/filtered_index_annotation_v2_print.csv
  - 20250811_Replay_FullPage/filtered_index_annotation_v2_replay.csv
  - 20250811_tamper_face/filtered_index_annotation.csv
  - 20250813_grayscale/annotated_annotated_index_annotation_mykadfront_print.csv
  - 20250813_grayscale/annotated_annotated_index_annotation_mykadfront_replay.csv
  - 20250813_grayscale/annotated_annotated_index_annotation_mykadfront_grayscale.csv
  - 20250813_wiseai_myid_test-dry_run/index_annotation_mykadfront_v4_print.csv
  - 20250813_wiseai_myid_test-dry_run/index_annotation_mykadfront_v4_replay.csv
  - 20250813_wiseai_myid_test-dry_run/index_annotation_mykadfront_v4_genuine.csv
  - batch_issue_20250910_bmmb_both_general/index_annotation_mykadfront_v3.csv
  - batch_production_20250830_20250903_myid/annotated_index_annotation_mykadfront_v2_genuine.csv
  - batch_production_20250830_20250903_myid/annotated_index_annotation_mykadfront_v2_print.csv
  - batch_production_20250830_20250903_myid/annotated_index_annotation_mykadfront_v2_replay.csv

checkpoint:
  enabled: true

transform:
  image_size: 512
  normalize_mean:
  - 0.485
  - 0.456
  - 0.406
  normalize_std:
  - 0.229
  - 0.224
  - 0.225
